version: 2
updates:
  - package-ecosystem: helm
    directories:
      - "/argocd"
      - "/cert-manager"
      # - "/keycloak"
      # - "/minio"
      # - "/postgresql"
      - "/traefik-ingress"
      - "/vaultwarden"
      - "/simple-fileupload"
      - "/routing"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

