apiVersion: v2
name: postgresql
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: postgresql
    alias: postgresql
    version: 15.5.*
    repository: https://charts.bitnami.com/bitnami

  - name: pgadmin4
    alias: pgadmin
    condition: pgadmin.enabled
    version: 1.28.*
    repository: https://helm.runix.net
