apiVersion: v1
kind: Secret
metadata:
    name: postgresql-credentials
    namespace: postgres
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:I7qv1BoCuiaz07Us7IqYrP9dvwCKf493gN49eoOwnJo=,iv:jxMV2iSLzWJCzPpZ8akdM5nPtiB7u0y/0KfgjoHoqGQ=,tag:huuGbUVxZF0xnzYc/3P7Jg==,type:str]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWk9WdzJOSk5YU0lZajJF
            UUhzNDFBS0RmZ0xZKzRrK3lmUlo0cXNhQ0Z3CmgrNUFNcTJWOGVtY3ZEd0x5b2VR
            bHlRNjFhV1dsRVRUQ2dlVTdmQmxxdkUKLS0tIFBNTHJHYXRJc0tQdnV6L0dWT0N6
            d1I5RWNVdSt0d0V5Wi9aZXJqZWVMQ0kK9xwP4mb5GAwUBtg4PTERzRmIh96AbHdL
            dt5bsyHAFDqIsm924Wl5bRFkFF9Q8NLGK61Z2vukv598sgxQpcnC7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T13:41:07Z"
    mac: ENC[AES256_GCM,data:BamA2Sv/r/xgRf8tWajxBEUaAktMAtoPOQrTwXKdsrHiJUU9qBUmhMxegQOr+ZKowrxhzSFaGfn/gnNGGtAtIUvpBfLyvJHWrD9bi9ty87A9Br7YcBbdSQKsfIbvoqwO4vMKHpTdKEz/X0eCq5GFCxUVjeYvAZd1og+owWvzuIA=,iv:CL2Ki54QSMMTeqNNxS106ZQ4jkjvnhyTLffIR2GPM3E=,tag:f5BAJJSLbbrNMlj/3kZunA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: postgresql-init-scripts
    namespace: postgres
type: Opaque
stringData:
    keycloak.sql: ENC[AES256_GCM,data:rieZEPFRRfpiwZ2MCjmClZDjv1vSFWYlK+xGSkFqHlCgXMXr64pZYGtS5S88NtrDm3rpQP7rL/e/bMC4ttO5foRmNMW7oz83SyWMvSFw8xIXOh7yZg9L33Y/GRlvfKBjEhmfppR3UOobRVAzZqKT0QmhYqvyM2Ta75DRQ+QvCMFXnfYirIXBPoimmHtU10K/4js+0TzzPn3v92Lh3pAlgmta5yKkJVcyuirvycwGAoh/Icio+U5ysMh+oaTs14nZmUsylSJGoieRmhZU,iv:hnS9XexyLUgOCm2TqF1nNS54Av4WD1CznbqlGSBI5oY=,tag:DAXibOVE8NXKyzyOGECDlA==,type:str]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWk9WdzJOSk5YU0lZajJF
            UUhzNDFBS0RmZ0xZKzRrK3lmUlo0cXNhQ0Z3CmgrNUFNcTJWOGVtY3ZEd0x5b2VR
            bHlRNjFhV1dsRVRUQ2dlVTdmQmxxdkUKLS0tIFBNTHJHYXRJc0tQdnV6L0dWT0N6
            d1I5RWNVdSt0d0V5Wi9aZXJqZWVMQ0kK9xwP4mb5GAwUBtg4PTERzRmIh96AbHdL
            dt5bsyHAFDqIsm924Wl5bRFkFF9Q8NLGK61Z2vukv598sgxQpcnC7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T13:41:07Z"
    mac: ENC[AES256_GCM,data:BamA2Sv/r/xgRf8tWajxBEUaAktMAtoPOQrTwXKdsrHiJUU9qBUmhMxegQOr+ZKowrxhzSFaGfn/gnNGGtAtIUvpBfLyvJHWrD9bi9ty87A9Br7YcBbdSQKsfIbvoqwO4vMKHpTdKEz/X0eCq5GFCxUVjeYvAZd1og+owWvzuIA=,iv:CL2Ki54QSMMTeqNNxS106ZQ4jkjvnhyTLffIR2GPM3E=,tag:f5BAJJSLbbrNMlj/3kZunA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
