argocd:
    configs:
        secret:
            extra:
                oidc.keycloak.clientSecret: ENC[AES256_GCM,data:7L7UyDf/EAT9NJH2ImA5BocmQ8yvdci/12rd6dGQQA4=,iv:KloduiFCGJPtruIDzLAIr+xJsYo27XMp3af9LKuyPPA=,tag:a60unHM58FXAwN75tuWQfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWakdWam41akdVNnRvYjJG
            OXNNbXFGeEh2d2lKZGQ5Q2llQ08yVjdabGtrCk1OdlNMNnlDbWtEeE9jRmt6ZHNK
            M04vUm50MGRGVjVZU0FGNzA5NXRtbGsKLS0tIE1pUmp1bFUvbnJBUmxFcGR5dnc3
            RzBGbWsrVmhKK1BZRWZCT2lWeUNIaWcKJoyijQTY3KnIN+5TSLcNSsv6+zjw2PGD
            uV8DBuXgapUMH7cvqNV1mj5bK/Kn8lB3qoA1XZBkEy86S9eDSfVmFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-10T21:24:41Z"
    mac: ENC[AES256_GCM,data:yR91v0zg5R+fysMs3igCoPEmrlHwzUh6xKiHZi2dfxhJWh1GgGk9sS9uihy/sN83LyvMmUCanIS4IAtaQP3HBK7uK8HuHBVrU1hSAwIDcsWoRp86tyR0VFwkrc/VKY0SXmLUPfaa4shZfCkDHF2rgD3kP+S+KZy65ayAIWClpM4=,iv:k7xQ7Ws1es8J7mTKyXuVaBvLuO20OCbcTdbZYPoO2gA=,tag:QDjfQpwLz8lIo24wRpHmSg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
