apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: external-dns
    repoURL: https://github.com/green-ecolution/k8s-infrastructure.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

