apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: routing-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: routing
    server: https://kubernetes.default.svc
  project: default
  source:
    path: routing
    repoURL: https://github.com/green-ecolution/k8s-infrastructure.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

