vaultwarden:
  fullnameOverride: "vaultwarden"
  domain: "https://vault.green-ecolution.de"

  image:
    tag: "1.32.0"

  ingress:
    enabled: true
    class: "traefik"
    tlsSecret: vaultwarden-green-ecolution-crt
    hostname: vault.green-ecolution.de
    additionalAnnotations:
      cert-manager.io/cluster-issuer: cert-manager
      kubernetes.io/ingress.class: traefik

  serviceAccount:
    create: true
    name: "vaultwarden-svc"

  data:
    name: "vaultwarden-data"
    size: "2Gi"
    class: "do-block-storage"

  attachments:
    name: "vaultwarden-files"
    size: "2Gi"
    class: "do-block-storage"

  smtp:
    host: mail.smtp2go.com
    port: 2525
    from: vault@green-ecolution.de
    fromName: "Vaultwarden (Green Ecolution)"
    security: "starttls"


