pgadmin:
    env:
        email: ENC[AES256_GCM,data:XLlFm1FaI6jSswhhxrzoP3BqSxHsdLV0k68=,iv:8CAZRayAdA9FORWhhP3Kh36iTYngihLQLTtqthBcnKU=,tag:pQlaogpMLE6SjO8uhNm6kg==,type:str]
        password: ENC[AES256_GCM,data:ecMPRI7NkRr737Ip1adjaqD2MT4SNRo2q0baMqztapo=,iv:iJcN2mrOu1oTwyOO+M67AfUu1lwLnY3k/9uxG3CfHz0=,tag:x2xYnFrTT/224Oe6c3CXwA==,type:str]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTHFLNFRoZTc3c3F0TGFx
            dlUwV25jQktkRXpTS1pJdVdGVXZJQzJoSFVRCnZxM1hVSjhJN0E2MHBFQkQ5Nkxl
            ay9mdGNNMks3SXo2SjB0elUxR1pUUEkKLS0tIGhENEFlYnQyWS90WjV6NWJWYyt5
            ZmhFWHBZaHlvb0dFQWhHQW9pczlZQ2sKGi9J5yu9cH77G7akoiCHL4lLrJwnKADh
            oBCjz/4KqaEBA0HlKUih3l2zmZmOACfHCp3E3CNWWWQmEdbWpO8DlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T13:43:02Z"
    mac: ENC[AES256_GCM,data:QKF0bLquVnYoa5BfN8sqO/vxnbt/PE8ceveVW0xeF5bh8anQggRYSzkA965mXyjjejCfsjnZMiKDUsdkKLpWZ/t/Pt1geeiEK2hlBG6/jbA15vs7z7KV4wlC5KzNE0TBPSecuYPO9sBOJbLeESCEx0Uy+x4Mz/QYzHqM43/YRCo=,iv:ILriuNGIT6H36deOTlDHm0j+U/TgngI0m9gcJx/x1B4=,tag:tiiN9THBGeWdv7Q9zJtQog==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
