minio:
    extraEnvVars:
        - name: ENC[AES256_GCM,data:l46Kq4Iqxzz4WXr5+Etv0ohu6caoPYWXtIgd7DFzXA==,iv:XFfUnACZPP44bDFYUrqIxTMLKwcM7YT8gyksJ9hSqkU=,tag:OeKmOTB/aiVydlXX9L7/Mw==,type:str]
          value: ENC[AES256_GCM,data:b7qRd4u3N9wG,iv:RIS86Lh2OEBk81XO1NFN9Ct2mzls34IN+tHfEtO50mk=,tag:v/hy2BbupLVZCxa8qHXoog==,type:str]
        - name: ENC[AES256_GCM,data:RsvpkZTMP+HpUhUINYkDhw+L0i1QfvqQAUJh5eg0VCWL9nQ=,iv:pATqYoo5hHvRbHkAZqYaT8ygp6sB9XAT8+4r2IVOwis=,tag:EnVTsIDQmdVP1gJ1wqsXxw==,type:str]
          value: ENC[AES256_GCM,data:Am29URLnO3LRDVK2Uo3R+sKSduU59mqawhenC7mMPtA=,iv:fAsu/U7eawgegC5odhl+hVV6vXi2JKBuwlY2RehItUM=,tag:yguQtN4fmaGXCcLfzqLwmQ==,type:str]
        - name: ENC[AES256_GCM,data:cfWVx1N9N1Cc1Jl0FDAjd5g1sFQ06q7ZNDEnOMEBxcM=,iv:G6/SLUx4DJ4LJAv1JZ1P+PeZyJf5FFgv0ae9w4eqVlQ=,tag:swlFCImy6IuFWiCi4CLziQ==,type:str]
          value: ENC[AES256_GCM,data:ay9HfbZoOE1g1WTRUbkvfw8Mvnajkm60Koarp/99NAPFVIS4s1MBqDGvkXEPlq1lpW1GkrAUfYwFlNpyOVIG/u4Np0sVtOacqzcpjMNVsob0f9C13PKfWJOh+A==,iv:9aE6eQJugfxKVXF+Z1xCeTuxjOwDF2wrL8QWRlFzj9g=,tag:BpBo2RCFvHs05vAFfE7Klw==,type:str]
        - name: ENC[AES256_GCM,data:ilKvf3A5CrIh/8VhRTxwiwd8EhOoM72v1P+/rw==,iv:mpPnpbu8t009IBM889Pzz3J3dV0i1rmCGQuix2MHZtE=,tag:tBlqIim9E8t/6eBnEw4xQQ==,type:str]
          value: ENC[AES256_GCM,data:FSpbBFaxf3SgJTmySg==,iv:069rWQ7C5inESUNzv0Qlf9uxpu0NE3Z7SQik+oJkX1I=,tag:jpx2225YpMzCAVjLLyfFSQ==,type:str]
    auth:
        rootUser: ENC[AES256_GCM,data:qRBMF2E=,iv:+Xpsesmy75OLfc+SuG4paQWQ1GoxnVRur8Okaq+BKXk=,tag:cKz2i++8JeNm3wxNVM5gMg==,type:str]
        rootPassword: ENC[AES256_GCM,data:koxED+RAMGYNqRI3bymr3IC9MFFLFGipwg==,iv:XsneXhIi//FfqukK3iQbEYrGDRRC850r+uHJIbd5B+Q=,tag:J3k5jhgGQU/JnhRGAzHI9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlemxIZzJxdm5Wd2tsWnJ2
            bDc5amc1b2RSY1BDTXZYNTZ4SzVhVWZoemxRCjIwTllqSkoyMGkvU0o2OHZwcU1i
            c2Mrb0JJVmFFdHgxRHg5aCt4RGNVYXcKLS0tIGN6a094d3AwU2FFS0oydUdhYVZC
            Q2hxdGZQdFZ0c0dqbmN1NWJuN2xRMGsKZopX6N3/rFkgaHxQHk+G/1gMzOlPTFTH
            SU2XeDwmyqCzav0MLap37sovsdd9Yv8zbYdrMX+cCUj7T1kv3t1x/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-10T20:55:37Z"
    mac: ENC[AES256_GCM,data:Fopy4uQ9pwqZWSwVU1MI4t371UcH6Ik4bnARr79FwLOgH3bQ2Gs3YXXUjN1186sThZm4gqsg1frdEFHSfAtW7aOC+wxVduIKNrNyiJdmEQ2RkcgXPTArNX1nzzX2STUqiVBFBhtYuae/xwrMF+ZiLAJVz0tOwN5+FbgoYYnt6YA=,iv:NnF7A1U7iLFZ1s3cSy1axxVa6uiPNVZirdv8Um8mXas=,tag:tNFyhDXSCssXl6mrFl8G7A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
