minio:
    auth:
        rootUser: ENC[AES256_GCM,data:74pqNQg=,iv:fRr8ihAmUOhshMTNh9vXZJQ6cwBx2mKcG3MuWxjfWp8=,tag:dy4MPpgTvHdinYbD2n5Wig==,type:str]
        rootPassword: ENC[AES256_GCM,data:Kdwd0r+0jc2XAHzHu1j5c5CahMwPQQzslg==,iv:qMxyQse70W/60thDYEUKQNklMinjVyTOZdVBboMQzSY=,tag:uDxmAPgtLZ1D27xINK+9vQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSkFVKy9sV3REVXpoSEZy
            NldsK1U4MnNyaHlhbGQvNHcyNk41bzNYYW5NCjdFeE1oZGs0K0Z6SXJXalBodysr
            RGFKL3ZsWFRJeEJNc1FLRHNKR2FQcEEKLS0tIGdTMlY3cUxXbFlPRU9wTFE5L3hY
            QkNCeDJ5QjRPVUZiNks1Mmp4bGZuWmsKmHnxJk7Bme0x52aSTVHi0D3gZZj25LKy
            IkcUw2GS6F9X8C06dI1w2TdPY6BHCRAvYEiXzA7Zk/H3hfm3aQwIyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-10T16:50:44Z"
    mac: ENC[AES256_GCM,data:kuy0bc8nABNezXr5T59HM9eMXxfzu7ihtkrjVQNQ87yPXLrrZpTxtwF88pg1+9w7p2XFt0T/JYOcVgSwE088qzJwcEtivb3rtxvsWZCFcNF5iz5Ci4g6e6wFbKw+rHcIySgKlIJSWP7fDDrOnkFdl1Qe6ljrspCc5oviOhkzAUE=,iv:hKd13ufXS6twgKJ4eTP2yHYVTkR8P/LLmPFhsiL/h6o=,tag:AxBPInJn84X0FzvvrtkRlA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
