minio:
    extraEnvVars:
        - name: ENC[AES256_GCM,data:IKotutnPyWjGjU3XLEdgMMs+ZWsxCDFL6D5U6P//43llQhxbRyiSWIEQJRjgjACL,iv:hh0AGzhiOluoXa4XgENcqksXHoBasMG1Jz7VYXVePoE=,tag:b9L4f61R+R0Erg7Ivv/iIw==,type:str]
          value: ENC[AES256_GCM,data:Q2S6/B1MNlDn,iv:9q/e3gPOvvCP0qDzeqY4l/aXhVDkVSzwvIaxZAPM6Kk=,tag:xx5ldhk3U0wNO6MTF7xIWg==,type:str]
        - name: ENC[AES256_GCM,data:d2l0jZ5i7VPRCCLytO/m1GUOEdPn0jJ7fJCmB02oubYtd0um6i5ExXjxLRhY3TWa2TEo0g==,iv:3Ve4trbTDcjgUQs8i7ClyYwQdI7BzhU/gy9aagN5cO0=,tag:e2rGqNCBLXQYPQo13IKF0g==,type:str]
          value: ENC[AES256_GCM,data:Pvm6hTVbASsanZJoJaNwL2HKlBTO4d/dy+7zWXeDZ1s=,iv:ojsS9vWPK3pkmnDB+qsZE1P881jknmK8oISaeAiHGuY=,tag:rSkoY435FrXA5UbJZLfqGg==,type:str]
        - name: ENC[AES256_GCM,data:6JXaTDD2soMhza9DN05QiNuSfy8La1cn0Sc5BDCJ6PlhqIzqkoPAAHDsCqfN1PLh2Q==,iv:mqQqflKEHk0YM9ML/SPhT6hqyrC/PhLmmIJT4xnP7l0=,tag:2KCYKd9eBBm9JArOoGrSpQ==,type:str]
          value: ENC[AES256_GCM,data:lqRANNZyWe6xOKBRpcDZ4zudrZMHH74fk2dUnvQ1SNZW06oKH63OYUJtU8WQb4++3UGkp+Yg9IoGesLUKEBwIm3Rjrqq6ANISOKzs4FMDz3g7bbTPEf03X5Z6Q==,iv:3r8smvbYQvCY7A08x05H9Y8Tc8avs1BybZKukHSU9xc=,tag:vpUsAaUCr9uZ0HqGJKAJnA==,type:str]
        - name: ENC[AES256_GCM,data:92W4gihnGiKmcL0Tv8oS6ZfYoL3GQhqWMN0oMhJnXQ0UsOsJ1cGozSnhOCVI,iv:ooEH4S1hkRKJLDcIK2/HnDseor5uBfieyr8vDfLzko0=,tag:U1YRj3mpcEte/ap780Okhw==,type:str]
          value: ENC[AES256_GCM,data:THZ4uefQ2VcDoCIC4O3XSwP592w=,iv:8YRXpOpbdJBkq73OZDyHcQgPxc8Lqa2gBdPftAtu97g=,tag:Jf2QJ1Ue93zvkRWIVdhyWA==,type:str]
        - name: ENC[AES256_GCM,data:KGpegyx6pzzlWx093WDqEbQSWCxA4YesAazYFH5sgiHuGcabSNjfqlxE3/01XWRmxbpRuCvgUceLJus=,iv:EFPmNJ+/AAJ1Z2W9ADViJP+q1kA1yu64RxWyMAYNxHU=,tag:9djX/yJGxD6vRE1Sym3nfw==,type:str]
          value: ENC[AES256_GCM,data:/mo=,iv:vCzPuWc48kw3lfLvXVCCzxkX7s9jvbhf55Ci9+BodE4=,tag:mQxCWJNoxZmRQe9idyQOlg==,type:str]
        - name: ENC[AES256_GCM,data:kW9ZjZfU8GqFef+OJ0x8vb8YSp21P8KS1ZoPdF+7E+Y65f+X6372ylEjMFebsdyc8+PN,iv:C6OFblEQmDScfgvK5ueuPtxYnJLb5WdRPQMqEASqVhY=,tag:Alg+rp9l1KiANr0iFwy5pA==,type:str]
          value: ENC[AES256_GCM,data:/XWoNmvWgTA=,iv:Xjk0tpB5brK9lRlFsfCdLasLY2sLGf+BcF2Rq7UTOwU=,tag:w1dNlO1raGs4/RjMFKRS6Q==,type:str]
    auth:
        rootUser: ENC[AES256_GCM,data:EIPfrdY=,iv:7JVOkrHCRxBthiwtw2H02/5+8+dP3SUK6z90x1T6R0I=,tag:5zILwT71ig0ecJzLHvIt9Q==,type:str]
        rootPassword: ENC[AES256_GCM,data:DMZQ/vqc9RkAIu6on5a2jTSytZ/udVJTYA==,iv:cLtMwcEi7538Yku7aEzUNnBGJB1CfyZOc9gyTfpP978=,tag:XgrSkC5D9T3DBkxBAkozyw==,type:str]
    provisioning:
        users:
            - username: ENC[AES256_GCM,data:2Lw9P2CZYM6RkvelAZmA,iv:4cOlHIkZ/apoohqi1SgRcPhui2Hy00ExTYQIcQm4dzw=,tag:fe7v6mo3u3asCj6XNssbyA==,type:str]
              password: ENC[AES256_GCM,data:NOM58UkzHx2eA78WL+nTW1OOjvlx6y2nyK6aMOXH7oY=,iv:JC7ONUpPProLBJaWTR99ctDTTfNQy/yB3UEHJUcmgQA=,tag:D9GP36d1dN5oBK7YpeLBCw==,type:str]
              disabled: ENC[AES256_GCM,data:IBd3HO0=,iv:l9q/bHLl3/R6ilWsQ4OUTy/f3gpDdZ+zKizjTUtrXGo=,tag:wq7wC0SohfMBrR+9LI9EUA==,type:bool]
              policies:
                - ENC[AES256_GCM,data:hhZQUb77wmGwTiCOWqGG,iv:tW5HbzDa6DkFhsNifoDT6fK61yYCT28AXjkkT18LjeM=,tag:b63tLaesJMMxH2XCu/ewKg==,type:str]
              setPolicies: ENC[AES256_GCM,data:8cmFvw==,iv:cMiow86Fc2cCRujwM5UDggoGdiw0SXaOrH7V7JomIqI=,tag:ADQEyoC7arJp+Us3QF2ocw==,type:bool]
            - username: ENC[AES256_GCM,data:2a+9bQ8qzLjZK2ujMusm,iv:tms1fwMGXKZ8mks0vCFFpv1yS7yAnyOoXfUv/UBt928=,tag:yKql+Ngm6kREu1Ua+VtbWA==,type:str]
              password: ENC[AES256_GCM,data:qckHF4IrEENb9rtDvCa6XqCyl35xHmsdalio6hCL6zw=,iv:LAQPcM6BxZRcRsc/EtGhE6OBsvwHW8B3iTzfeMHgSok=,tag:6vVJFYDCv77nz0B458ZaLA==,type:str]
              disabled: ENC[AES256_GCM,data:IBd3HO0=,iv:l9q/bHLl3/R6ilWsQ4OUTy/f3gpDdZ+zKizjTUtrXGo=,tag:wq7wC0SohfMBrR+9LI9EUA==,type:bool]
              policies:
                - ENC[AES256_GCM,data:Z5QhxkUwJ731tkF28DAp,iv:YstbLHBHTr+A8J9b38xLIoIvaIHMd3iBzdWfGnHVEN8=,tag:P5HdIdSH6aG9w0ZoyFCaCg==,type:str]
              setPolicies: ENC[AES256_GCM,data:8cmFvw==,iv:cMiow86Fc2cCRujwM5UDggoGdiw0SXaOrH7V7JomIqI=,tag:ADQEyoC7arJp+Us3QF2ocw==,type:bool]
            - username: ENC[AES256_GCM,data:A953zM0tis0V7hwn/fvYkw==,iv:v9mG7tbp9/+Fec4YfA9ujAVUeCN9FK0bkAX91W4g/Do=,tag:wg1XzkDRah9n1szIJfyANA==,type:str]
              password: ENC[AES256_GCM,data:MhpFT1oAeh7xcEwPlY/Y1erslZQILkh82J65BcpV6rQ=,iv:RgVQmXc6BNa2DRv2DckQ1xqW6/9R8To6+SHYQlJzDuE=,tag:9HD+bxYOPU/VJcBlkEpJvA==,type:str]
              disabled: ENC[AES256_GCM,data:IBd3HO0=,iv:l9q/bHLl3/R6ilWsQ4OUTy/f3gpDdZ+zKizjTUtrXGo=,tag:wq7wC0SohfMBrR+9LI9EUA==,type:bool]
              policies:
                - ENC[AES256_GCM,data:PR7joPv73pqAOUePGJ8NoA==,iv:vAVL0f3Y5bYID0RtYRXIy11F2Us0KkhA/L9eV1iuNvk=,tag:1qGrg0NDo+iFkZuiodc49g==,type:str]
              setPolicies: ENC[AES256_GCM,data:8cmFvw==,iv:cMiow86Fc2cCRujwM5UDggoGdiw0SXaOrH7V7JomIqI=,tag:ADQEyoC7arJp+Us3QF2ocw==,type:bool]
            - username: ENC[AES256_GCM,data:ZzfYtBt2naMsepxBGAg=,iv:QCXa8wxdr7O3vi1ta5eupboJWHSnhVs1BxZ55rFKZ7s=,tag:wbbm77cwNwx1pF5TIbj86g==,type:str]
              password: ENC[AES256_GCM,data:8RPGkukCUU5r2LymH28OjICj0AFzIGPCpICWF2J4UA==,iv:ecdX9sh/jF3GTuQWA3IY3qfcdoyxPT4DjFzyiY4TeW4=,tag:zV2I6Nnyf/M11p6vFihJCQ==,type:str]
              disabled: ENC[AES256_GCM,data:IBd3HO0=,iv:l9q/bHLl3/R6ilWsQ4OUTy/f3gpDdZ+zKizjTUtrXGo=,tag:wq7wC0SohfMBrR+9LI9EUA==,type:bool]
              policies:
                - ENC[AES256_GCM,data:x9Id0vAaNCWvVq68jrk=,iv:6YJhNqb2i6KgU3GN1sDfMv/OhYifhNlzZbpAr/DGSnA=,tag:VRd5voz3nAqmk+ZoNTp6dQ==,type:str]
              setPolicies: ENC[AES256_GCM,data:8cmFvw==,iv:cMiow86Fc2cCRujwM5UDggoGdiw0SXaOrH7V7JomIqI=,tag:ADQEyoC7arJp+Us3QF2ocw==,type:bool]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UXY3NCttVUt2ZEs1Zkhw
            b2QzWlhuU2d2RXpKdGIwRGk2NjZRd1ZzdjFRCjVlZmUxOVFQTlplQWY2TFVxek5J
            UFhsZ1MyOXRheXMwVC9MSkt1Q05MbWMKLS0tIE5uZ2NWY2JqcVd4cFV1SHhsb1pD
            MyswbDVGek9NQittZXV6NERnL2VvQkUKPtjsythMuGOlUQm3g3MOElnYvHfMmp26
            Q33bO17ITsJXXdc9Rox6umlxmnagly8B48Z/HfV2Qht+6JdeokSGRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-13T08:59:47Z"
    mac: ENC[AES256_GCM,data:mVGOM4xTkCpqhsJqMvDdPBwvWJ3IdV66aAB5cGF/2F6HQZFcOUKknZWouFKCGNleDU3FNQwMN4Knu608x4t8Q5eYl82Ef0+69te3iPE6iT5oS733N6tuqUKVSF63xl+8TZMchxmpJ5fnU126vyXIQlW3CKU26Jggp2ib9XDAQvQ=,iv:JUNxVN74SMxwJspc/6f6g6ycxTCfHM9qA4kRR8ut+fw=,tag:/f2zhX03vExIHeecT8NZFA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
