apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-credentials
    namespace: keycloak
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:vAeuyXoZnuk=,iv:5kdot30/mujF6Oit7KjERIRsYQ0SvgKKDIGWmmL6Vpg=,tag:Uh+GE1LsAlaPFHkGI8Xn5A==,type:str]
    password: ENC[AES256_GCM,data:RsoNR0linSmmt+9WEsxEyZtn9sC5l8FAbt7ZnNCUGAQ=,iv:ZOjzXOaoJ45ES1AAJEo22fykPZ0rukLxvM9rwxkZZXE=,tag:7rM/+CSLwPYFCG13Bpl3Sg==,type:str]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dkdTbllKdERQREF6UUwy
            MXVyaGtpV3g1SG5rc09BYWZzSVpueUJvTkRBClNCUFkwODdsWjBrTjh6YklSRHo2
            ak1sSnArK3VsbnM1RTBOVkMxTXlOczQKLS0tIGd4NkRyNHVmVVp1UFd6bVJmVldy
            RW55RWwxMlBQMXJhZ2FRSlFYSG10cjQKszisA1KAXvpSPluavMqIWej1QiryTH1V
            8xGi5jGLw5eQ2VA7C/aSUrBskONwtPjFYfVc0jJL8sUzjgFfqXu8GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T15:22:48Z"
    mac: ENC[AES256_GCM,data:ZCFw4zDt9yp/XANniKqHZ0qT8yCY4jEBnSx1Z1YtNfy+gcWO3qiQbuj5lAhc2xYMlAKP5yd6rh+v+PS4eLuDZ9fuJCMSyqvg7NMoSyv3lhMxmu4KDA7Q6ZFSZpoyEcmu15w9MUtDRFD5Fw5fKptPj8lkGFJMt8QZLSlVU2zhG88=,iv:7eNg5BhaUHx5ci4HqMJ2YljUDR8JcGAxiBbhCXeWuKA=,tag:A6cnyYmdA7V5fitngB35Uw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-credentials
    namespace: keycloak
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:XKiJgyM=,iv:pyRydpYZSsiFfSbbQfVBOqx2GxVStMiJuXls+LoQOW8=,tag:c9798qj+GP4np7VuJuNvoQ==,type:str]
    password: ENC[AES256_GCM,data:xgAJbyKdjq/dc0kJetKmItmOj1y2BWj/RqDx809xk64=,iv:IgxUWBm/7WROHXKdPJXh8U9snsHxlpTdrGkKCn/JMDw=,tag:Tb3NZw9E7Te4/1qQo6NXoQ==,type:str]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dkdTbllKdERQREF6UUwy
            MXVyaGtpV3g1SG5rc09BYWZzSVpueUJvTkRBClNCUFkwODdsWjBrTjh6YklSRHo2
            ak1sSnArK3VsbnM1RTBOVkMxTXlOczQKLS0tIGd4NkRyNHVmVVp1UFd6bVJmVldy
            RW55RWwxMlBQMXJhZ2FRSlFYSG10cjQKszisA1KAXvpSPluavMqIWej1QiryTH1V
            8xGi5jGLw5eQ2VA7C/aSUrBskONwtPjFYfVc0jJL8sUzjgFfqXu8GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T15:22:48Z"
    mac: ENC[AES256_GCM,data:ZCFw4zDt9yp/XANniKqHZ0qT8yCY4jEBnSx1Z1YtNfy+gcWO3qiQbuj5lAhc2xYMlAKP5yd6rh+v+PS4eLuDZ9fuJCMSyqvg7NMoSyv3lhMxmu4KDA7Q6ZFSZpoyEcmu15w9MUtDRFD5Fw5fKptPj8lkGFJMt8QZLSlVU2zhG88=,iv:7eNg5BhaUHx5ci4HqMJ2YljUDR8JcGAxiBbhCXeWuKA=,tag:A6cnyYmdA7V5fitngB35Uw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-client-secrets
    namespace: keycloak
type: Opaque
stringData:
    backend-secret: ENC[AES256_GCM,data:QujjqiyZeFGqKUkoKB51cGMnIwpqk1yMD+cIPp8uv/w=,iv:I9fFLMczZpwh4/oSKysp/9CQvVOND4JKKHMjrw/KHqo=,tag:YyFhhoyFSV1RD2QPUx6XKg==,type:str]
    frontend-secret: ENC[AES256_GCM,data:lu9A9lFSkL7lB6ulEfbNzlGtlEBwAALuNUyMpWknLlg=,iv:hcmGwh/OGdZ1pfN99YZPvnOLzI1nbqSyB+BVI5IuLDY=,tag:TVWe9m1YKDQs4LhC9XVZNA==,type:str]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dkdTbllKdERQREF6UUwy
            MXVyaGtpV3g1SG5rc09BYWZzSVpueUJvTkRBClNCUFkwODdsWjBrTjh6YklSRHo2
            ak1sSnArK3VsbnM1RTBOVkMxTXlOczQKLS0tIGd4NkRyNHVmVVp1UFd6bVJmVldy
            RW55RWwxMlBQMXJhZ2FRSlFYSG10cjQKszisA1KAXvpSPluavMqIWej1QiryTH1V
            8xGi5jGLw5eQ2VA7C/aSUrBskONwtPjFYfVc0jJL8sUzjgFfqXu8GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T15:22:48Z"
    mac: ENC[AES256_GCM,data:ZCFw4zDt9yp/XANniKqHZ0qT8yCY4jEBnSx1Z1YtNfy+gcWO3qiQbuj5lAhc2xYMlAKP5yd6rh+v+PS4eLuDZ9fuJCMSyqvg7NMoSyv3lhMxmu4KDA7Q6ZFSZpoyEcmu15w9MUtDRFD5Fw5fKptPj8lkGFJMt8QZLSlVU2zhG88=,iv:7eNg5BhaUHx5ci4HqMJ2YljUDR8JcGAxiBbhCXeWuKA=,tag:A6cnyYmdA7V5fitngB35Uw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
