apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-credentials
    namespace: keycloak
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:cB1Y0YHEOts=,iv:uOICHil7dxQPmSw0ycyO56q30xQp27c9kV1lL6WGFh0=,tag:ct42S9xSq/nN2jQ3Z3GJ2w==,type:str]
    password: ENC[AES256_GCM,data:4eo+d/T10EZp+bwediApgtVBgWL4/QjZwk/tOF1UFwI=,iv:8DNfB8oz6Kr1E+/fZt7jAgMyLyILT/+L0McmJcTQPaY=,tag:BV0sXuclfLFZH/9rhoDTRA==,type:str]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQXVVdGVUcGZ1cEdUblhz
            aVRuemh3V1NZOEZpZVJOK2MxWFFKMXBKSWpJClpIc1FTNS85STVleGhoamtVKzQz
            UVRYNGIrNXpZRTB2Q1ppN2tEcC9sNHcKLS0tIFUvcmFFeVlrYkZCU2JBR2UzUkVr
            V0Njd2FhY0JoZHlMTjFvT3NZTmlOM2MK5UOaTSyDA4J+8f47CZKhozjaxCM0N8Bf
            Fcmg0of2uw9a7ROk2VeEkUeP29G1gfclPpPzOC3jkBi1pR37CXMAFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T14:50:16Z"
    mac: ENC[AES256_GCM,data:awv8kfHVIlEx8KD63+xzCwjCX3flsXRvdjJa9nI3ud5W9HotZhSzpdPXPvMHCz0Z0SvIJruiFy3+NM3OHfBa4t7CKy2OTtjjc5RwSWShvnYCwAPB7LxMOyJ0/MCsVzoazgeVDwljeJDfcXzh6RE3lrUSXQYeamnPg++POQYkKls=,iv:wpvZC4w0S47dMycpf0NT85TPtyluveNrRk0f9na1JW0=,tag:ORYGcwjdTMtJA/JGnOGixw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-credentials
    namespace: keycloak
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:9zu99lI=,iv:Mr+ATN209BgJEJWNVZF+iAEKCwgJLw8ECR0rfwS+oF4=,tag:n1UiJGikvpCoaX0XWxFX2A==,type:str]
    password: ENC[AES256_GCM,data:p0OGswddcgv1wjY+gk+2ynSPvgJ5M6FhCd7kBp0GDEg=,iv:Uvlg4H2FhHfRUDELpBeQCfK1WY5Cp3ILoEkeocwNbB4=,tag:uMMA1nbEEOXWi1a7b8eiVA==,type:str]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQXVVdGVUcGZ1cEdUblhz
            aVRuemh3V1NZOEZpZVJOK2MxWFFKMXBKSWpJClpIc1FTNS85STVleGhoamtVKzQz
            UVRYNGIrNXpZRTB2Q1ppN2tEcC9sNHcKLS0tIFUvcmFFeVlrYkZCU2JBR2UzUkVr
            V0Njd2FhY0JoZHlMTjFvT3NZTmlOM2MK5UOaTSyDA4J+8f47CZKhozjaxCM0N8Bf
            Fcmg0of2uw9a7ROk2VeEkUeP29G1gfclPpPzOC3jkBi1pR37CXMAFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T14:50:16Z"
    mac: ENC[AES256_GCM,data:awv8kfHVIlEx8KD63+xzCwjCX3flsXRvdjJa9nI3ud5W9HotZhSzpdPXPvMHCz0Z0SvIJruiFy3+NM3OHfBa4t7CKy2OTtjjc5RwSWShvnYCwAPB7LxMOyJ0/MCsVzoazgeVDwljeJDfcXzh6RE3lrUSXQYeamnPg++POQYkKls=,iv:wpvZC4w0S47dMycpf0NT85TPtyluveNrRk0f9na1JW0=,tag:ORYGcwjdTMtJA/JGnOGixw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
