pgadmin:
  fullnameOverride: pgadmin

  startupProbe:
    failureThreshold: 60
    periodSeconds: 5

  VolumePermissions:
    enabled: true

  resources:
    limits:
      cpu: 200m
      memory: 512M
    requests:
      cpu: 200m
      memory: 100M

  persistentVolume:
    enabled: true
    size: 5Gi
    storageClass: "do-block-storage"

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cert-manager
      kubernetes.io/ingress.class: traefik
    hosts:
      - host: pgadmin.green-ecolution.de
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: pgadmin-green-ecolution-de-tls
        hosts:
          - pgadmin.green-ecolution.de
