vaultwarden:
    adminToken:
        value: ENC[AES256_GCM,data:H+Zr9lczpTa1mXNPqC5iHWyS4H2zOxYqXcMZ+zeKfh2qYuisIXez0P7fzzkIUM8T0SeFxJRteNvSRjgH2NGhIDbdGTf3thuOKhz+V95DXaadZeJHSoXXVZJsvVa97RNe1d617kIY26vxc34wf+kRld+D8Rhl0i7n7deBuYFf/SxfhFMmqp/Qhe4xcA==,iv:QYyLEavdphQFHqMWsFf+zXREHuEikVFCE8QL/AX6zqQ=,tag:IL+eA0LOyhLwe5o0kBhecQ==,type:str]
    smtp:
        username:
            value: ENC[AES256_GCM,data:JIYYLS7cnRP8YTMz/ziNZfK3RkXVonKk,iv:hUVYvarI/aghfRtShmqa3Mn1aR9EOJiOl4YrUBX7Njo=,tag:yXcm6csntOyvAX0Cde1W+g==,type:str]
        password:
            value: ENC[AES256_GCM,data:1GP3X78yH1wh4RjfmWVdBQ==,iv:l9Dqw602JLwqKXgFW5FT7Mu1fqF2IlJalJKfic5PP1E=,tag:7YG5AjqlkdNsX5xfQGZSqQ==,type:str]
    pushNotifications:
        installationId:
            value: ENC[AES256_GCM,data:7kQZdX3/Z7A57vZr//TEjzZENyfgvaN0lel1in2NxAJ2MVku,iv:24FRmPHjHWm/o0hOvEaDswWcFosZ+YqlTc8xQipPIjw=,tag:jlzObZAReFgOx8GCyr7UJQ==,type:str]
        installationKey:
            value: ENC[AES256_GCM,data:J1Y1c4dWPgiqyAdmAHfvDB0NOpg=,iv:u3CKBSUwoK4o6gNjgzpRfgEBZs5C2rf8SXMTjMfMW7g=,tag:1w293TOk7nec63hH1zGirg==,type:str]
        relayUri: ENC[AES256_GCM,data:59pOD8Tfkm/vfFjFho9GxohlCexdKBZNW4M=,iv:8BH24EKmTGDWY3wlUt16BxUISGAlZXMDEBzhihsbsV4=,tag:n9n+Q1HcpJlBi3F0/IT9iA==,type:str]
        identityUri: ENC[AES256_GCM,data:+Ds+v025Sty6wb2FCH0lV4spbHb34av+nIcP6Kaq,iv:kp4Fo9lCAFwKjcnS0/JUCmejV8prY5Bej9/c9hm8AzE=,tag:MP67TIqIgl4tUHZQpN/PvA==,type:str]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRk5Ic0x3UGl5Vit3S2dj
            a25tVGhGTStienFsOXBxSFJOSnZhamxiVW00CldGUGxEY3BNZXNYbzh0T0pEMDJh
            THhKV0ZwU2E5K3UwdDRURWI5Q3Z4aVUKLS0tIHhvNXJua3lvRjQ2RjEvaGhGeXRK
            VEZ6U2h6ZTU0NVVCQkIxLzlOZk9lZTQKtzoggiYACvdPqgDBykD/Jk3u92Aqrp5t
            Xw6okO0BXfHKh+gFmTob0xM4/AiAzkggvtex1iIqzC0vaj3npdQioA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-27T21:06:15Z"
    mac: ENC[AES256_GCM,data:6QeErc0NETFQzuEqG2woRXaveBTIypCQ/wJXs7LDtQecm1raRdKYTZ/G5+ceHhKcGGo+XiKl6J+o3mC8Wu75aOxSO6GeTqC6OBHdtqT1XRrvLxkJtvsdCbEyjovyrkMi6L0HcDNkjM1LGIj/+0Jb63FnCnLWZQoUvs7hM1rIbdY=,iv:rIvprmlL91OnZPMkHBcSinb56c1+Wsf8Vg+L4kp8QzU=,tag:bXJx7eqLOTH4JjnCpKeueg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
