apiVersion: v1
kind: Secret
metadata:
    name: minio-env-config
    namespace: minio
type: Opaque
stringData:
    config.env: ENC[AES256_GCM,data:aBoGA0RqWcB00Uurg79i4n7HOIyXQDI/HlQwzdUDUjZ45BOsWZ1vugxvmicv2qkMc4TT21G9Abcztn0ajryd5RcbFmLoNA9hYaErFxwU03Qc+g==,iv:sRP2z1QsobB7SXndTe/QzY3KOXA9wTnlXVxmEDHXg5U=,tag:wjHUlpnhXv4Gf0E15bHQSQ==,type:str]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSEpxb0NPVFVzQ3pkQW9E
            ZnJJSEZaRlhNbWRmSlRIaHlxNlZ2S0lscGdNCm1tcWFOSkc4UVVuQ0ZlRG05Y1JE
            aTE4MTlwUGRSQTE5N2JVajNWbXRBeEUKLS0tIFVKY1lrcm9OcEZGRWRLV0dzK0hv
            SVl1UDgyanFiMDY5RTlwWUpsVUFlYnMKhsw80E0ELne8DE5sYQZRJ9I7W3uOIbDl
            o40HBorWmyYdGa/JCgbolSq7N8h40vZTAq6VYuAAxWb/h8b64q6UvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T14:14:11Z"
    mac: ENC[AES256_GCM,data:hHqOuYKu5yCZ4nneMS3zt34tQL9Ul22Fp3OPv2ZLYYE+/EZGznImqz+iPsOCgQMV6SV8/Qna5Ib8qO6fHQ0di0vKtjvrLQoeSiQEXsQBZTA1QiHJdy6VHV2csyUyjUk/y5gnmLRfbXY/soyTwbqkPBWHTLQSAcihMaCZoXdQWGE=,iv:bqoxJrBuqVdB/MDElXBY81ivdFcRU56Q1ZedSDrH8D8=,tag:YZAhWvjc66ZZiYJs7TKLyQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: minio-oidc-config
    namespace: minio
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:KConmI5O25cQ,iv:qXSTy8DAw1v3xOlFBVEi8Av4DGj6J5efNPU6zDxI7+Y=,tag:nKRyo95un1lqb4FNf0ibfA==,type:str]
    client-secret: ENC[AES256_GCM,data:rO8sp28yU3C0VOo6s4jtxTjoXABVjBysB7IyKKOH3gY=,iv:Pfnwmsnv7+w1a2zidqNh/d3UT9HbWrNxN9ZckqWN8S0=,tag:/9rolb6meiFmYNWpFjQjZw==,type:str]
    config-url: ENC[AES256_GCM,data:n+QhB840oN4lK/QO3Dtl6nrc2hb4nQNjO1QByuMuATErOoQSQY+u0vJ50C78/q6sSp39Oja/NC6A0Qx5G8Y514hNMogBjeHmc5e++ldbTXY7OxLCcsHTQl6T1g==,iv:sUu8CQw5r25ZdtM67/+AnhVVISaM/LrwGIo2AtueKgY=,tag:putKYGMHG56PEtxuP1R4tQ==,type:str]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSEpxb0NPVFVzQ3pkQW9E
            ZnJJSEZaRlhNbWRmSlRIaHlxNlZ2S0lscGdNCm1tcWFOSkc4UVVuQ0ZlRG05Y1JE
            aTE4MTlwUGRSQTE5N2JVajNWbXRBeEUKLS0tIFVKY1lrcm9OcEZGRWRLV0dzK0hv
            SVl1UDgyanFiMDY5RTlwWUpsVUFlYnMKhsw80E0ELne8DE5sYQZRJ9I7W3uOIbDl
            o40HBorWmyYdGa/JCgbolSq7N8h40vZTAq6VYuAAxWb/h8b64q6UvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T14:14:11Z"
    mac: ENC[AES256_GCM,data:hHqOuYKu5yCZ4nneMS3zt34tQL9Ul22Fp3OPv2ZLYYE+/EZGznImqz+iPsOCgQMV6SV8/Qna5Ib8qO6fHQ0di0vKtjvrLQoeSiQEXsQBZTA1QiHJdy6VHV2csyUyjUk/y5gnmLRfbXY/soyTwbqkPBWHTLQSAcihMaCZoXdQWGE=,iv:bqoxJrBuqVdB/MDElXBY81ivdFcRU56Q1ZedSDrH8D8=,tag:YZAhWvjc66ZZiYJs7TKLyQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: minio-user-credentials
    namespace: minio
type: Opaque
stringData:
    CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:J8YZK0I=,iv:WXlNkHOyfrel2kAWTavRjQJgSdsmkNTborEoEBDfuGM=,tag:MbW75wC85QCZ29SSk7pleA==,type:str]
    CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:tq6sFXdiP1UyTtNFYFeiUdK8R7XJX1d0wg==,iv:cLaMm2WihjEM1+pZSKHHsL7Y01OnGd4xmRcb3AO8nAI=,tag:qUiTjkxzfO/3/7+S0Bk/QQ==,type:str]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSEpxb0NPVFVzQ3pkQW9E
            ZnJJSEZaRlhNbWRmSlRIaHlxNlZ2S0lscGdNCm1tcWFOSkc4UVVuQ0ZlRG05Y1JE
            aTE4MTlwUGRSQTE5N2JVajNWbXRBeEUKLS0tIFVKY1lrcm9OcEZGRWRLV0dzK0hv
            SVl1UDgyanFiMDY5RTlwWUpsVUFlYnMKhsw80E0ELne8DE5sYQZRJ9I7W3uOIbDl
            o40HBorWmyYdGa/JCgbolSq7N8h40vZTAq6VYuAAxWb/h8b64q6UvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T14:14:11Z"
    mac: ENC[AES256_GCM,data:hHqOuYKu5yCZ4nneMS3zt34tQL9Ul22Fp3OPv2ZLYYE+/EZGznImqz+iPsOCgQMV6SV8/Qna5Ib8qO6fHQ0di0vKtjvrLQoeSiQEXsQBZTA1QiHJdy6VHV2csyUyjUk/y5gnmLRfbXY/soyTwbqkPBWHTLQSAcihMaCZoXdQWGE=,iv:bqoxJrBuqVdB/MDElXBY81ivdFcRU56Q1ZedSDrH8D8=,tag:YZAhWvjc66ZZiYJs7TKLyQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: minio-provisioning-credentials
    namespace: minio
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:cvOnbEg=,iv:ZYXBHhtFSYMHJ0gGEajECEkglEXowF7nBwxK11LJenw=,tag:7AlV9r7eRTxCnoAfjzYgSw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:L33I5P7zpgmvIlbckenV87oiFzhehXf9eA==,iv:kY3cz3RZq93oIqz8QXkSQSV5rAR2tv9awc1jfce2EXw=,tag:YtErbEaYB4eeL/0QE2THcg==,type:str]
    USER_ROUTES_GPX_DEV_PASSWORD: ENC[AES256_GCM,data:7V6YUoRWlwXdlbOtlZ1NYioQbRdkFJa/PIDghk0Gow==,iv:AxHdPWJhLlPEGo0l9go1oiOuaWie36hsKWcGyAFONfI=,tag:WRcRythEyVPABnMyFiD9VA==,type:str]
    USER_ROUTES_GPX_PROD_PASSWORD: ENC[AES256_GCM,data:0h9BWX9JRA4OAK64Ag6o5ndzHcUMXnXcM5HpRe3TXkA=,iv:mg5CQ0X9g7bUslzr0Jxhhknahml/7C2x4QS/E6dILPk=,tag:oCh22hN0uB1AGasnVKvhdw==,type:str]
    USER_ROUTES_GPX_STAGE_PASSWORD: ENC[AES256_GCM,data:uKzyQElLfXcGvHt/UlIdyxhe2OvjCddpFylr/tG1U5E=,iv:I8kaaGmrbC0Wfp66ZECkfApuVBfUQaatc42Tp3odfjk=,tag:bqzXS0FRQmx7/ShQePfkVg==,type:str]
    USER_ROUTES_GPX_DEMO_PASSWORD: ENC[AES256_GCM,data:OcE6UGZNy6fSooMzOpXeg7hOD34u6EclkRTssw5w6Ms=,iv:GVc1ijQONxCsn80R55IUgH/UwmnLLArlo7/llfAkybM=,tag:zX2dkyapFujomoqTNb+TJw==,type:str]
    USER_STREAMLET_TILES_STAGE_PASSWORD: ENC[AES256_GCM,data:TqQoER+ESRD14rkUnAcDogRBKlEolh5YBkbbOiyBpRI=,iv:Wr9elFDk68Fm5vMy8b15XfIx4CpRqmcUqPBBd4gl3Cg=,tag:7g2f+O2MuMaLfJbiEqCMpA==,type:str]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSEpxb0NPVFVzQ3pkQW9E
            ZnJJSEZaRlhNbWRmSlRIaHlxNlZ2S0lscGdNCm1tcWFOSkc4UVVuQ0ZlRG05Y1JE
            aTE4MTlwUGRSQTE5N2JVajNWbXRBeEUKLS0tIFVKY1lrcm9OcEZGRWRLV0dzK0hv
            SVl1UDgyanFiMDY5RTlwWUpsVUFlYnMKhsw80E0ELne8DE5sYQZRJ9I7W3uOIbDl
            o40HBorWmyYdGa/JCgbolSq7N8h40vZTAq6VYuAAxWb/h8b64q6UvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T14:14:11Z"
    mac: ENC[AES256_GCM,data:hHqOuYKu5yCZ4nneMS3zt34tQL9Ul22Fp3OPv2ZLYYE+/EZGznImqz+iPsOCgQMV6SV8/Qna5Ib8qO6fHQ0di0vKtjvrLQoeSiQEXsQBZTA1QiHJdy6VHV2csyUyjUk/y5gnmLRfbXY/soyTwbqkPBWHTLQSAcihMaCZoXdQWGE=,iv:bqoxJrBuqVdB/MDElXBY81ivdFcRU56Q1ZedSDrH8D8=,tag:YZAhWvjc66ZZiYJs7TKLyQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
