minio:
  nameOverride: "minio"
  fullnameOverride: "minio"
  namespaceOverride: "minio"
  global:
    globalStorageClass: "do-block-storage" 

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cert-manager
      kubernetes.io/ingress.class: traefik
    hostname: "minio.green-ecolution.de"
    path: /
    tls: true

  apiIngress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cert-manager
      kubernetes.io/ingress.class: traefik
    hostname: "s3.green-ecolution.de"
    path: /
    tls: true

  persistence:
    enabled: true
    size: 8Gi

  provisioning:
    enabled: true
    policies: 
    - name: routes-gpx-dev
      statements:
      - resources:
        - "arn:aws:s3:::routes-gpx-dev/*"
        - "arn:aws:s3:::routes-gpx-dev/*"
        effect: "Allow"
        actions:
        - "s3:*"
    - name: routes-gpx-prod
      statements:
      - resources:
        - "arn:aws:s3:::routes-gpx-prod/*"
        - "arn:aws:s3:::routes-gpx-prod/*"
        effect: "Allow"
        actions:
        - "s3:*"
    - name: routes-gpx-stage
      statements:
      - resources:
        - "arn:aws:s3:::routes-gpx-stage/*"
        - "arn:aws:s3:::routes-gpx-stage/*"
        effect: "Allow"
        actions:
        - "s3:*"
    - name: routes-gpx-demo
      statements:
      - resources:
        - "arn:aws:s3:::routes-gpx-demo/*"
        - "arn:aws:s3:::routes-gpx-demo/*"
        effect: "Allow"
        actions:
        - "s3:*"
    buckets: 
      - name: routes-gpx-dev
        region: us-east-1
      - name: routes-gpx-prod
        region: us-east-1
      - name: routes-gpx-stage
        region: us-east-1
      - name: routes-gpx-demo
        region: us-east-1
      - name: public-videos
        region: us-east-1
    extraCommands:
      - "mc anonymous set download provisioning/public-videos"

