minio:
  nameOverride: "minio"
  fullnameOverride: "minio"
  namespaceOverride: "minio"
  global:
    globalStorageClass: "do-block-storage" 


  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cert-manager
      kubernetes.io/ingress.class: traefik
    hostname: "minio.green-ecolution.de"
    path: /
    tls: true

  apiIngress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cert-manager
      kubernetes.io/ingress.class: traefik
    hostname: "s3.green-ecolution.de"
    path: /
    tls: true

  persistence:
    enabled: true
    size: 8Gi
