#ENC[AES256_GCM,data:RdE1wiIFX9B2bFoKX6luZk/AsllEyVLMpYFCopSsFNVJX7Xv3s7I1ZMU5JB2u4NGgrtBkodsfSB0XA==,iv:XIW2b5iKT09S/xkjVgmaun4mZB/zjVWU57zDCj3RMwc=,tag:GquLsL5EtTdNEWjF/UGeaw==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: basic-auth-secret
type: Opaque
data:
    BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:gr6hU00g+x935cqC75YvC5MUMR4=,iv:xuZbWjWq7cCCWkKrVjzDe5z8y3JCxd0O9/dctpVrKwM=,tag:uHZliwnUrPCAcWvlF3oePg==,type:str]
    BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:2Re4uXDmZ4Y=,iv:R90c0/vZ6ICz4KnjA4Iu2v1aOr7IrQpHAdM8lKKcuxM=,tag:ix25LFq9KqEkzLt/M7MdzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSnBZSUVteXhrdmVoUUdC
            M0FFTXV0cXE5eWNUa2VyS2hvNFVnN0dNbFVrCnZvWHh1Ykc4dmxmcEl1V3RSTzEv
            MEplS0tpa1lsbTdQZ0RwS2h3dmxYbmcKLS0tIGJnRE1WOUtabExacktFTU5vb2xO
            MzRaQS9EZ1VsSUxFU1hIbVVyelJkMDgKQvN0xz4I0EQ/gP0sd+jxatKNIPsVXgze
            Mqv+sPPnhprS1mdmXvto047J+Aa3J5an/yqLE8jO4HBTp1asm1UQFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-12T13:29:03Z"
    mac: ENC[AES256_GCM,data:0S06vF3qEMq3KyXX5QUsP5e269Ek7S1O7tqKJ6wW0nbYce9LheiYqsmjtIhihk6mRIg3vs7Qlu8FtQQ9Jfudw9+RRPVvtXLxRovNdVYggbxEldkICsQpXTYGOFPjKdscOiRTJlo5I0s7tBurUsbTzFBzJVwWD81ZCoT9gPlJKk4=,iv:3bc5P7dy4txJ7NgIGVdwNc3SThpwvy2mgtXZ57eZAT8=,tag:CXq2uB8bM/L9WHAmIVJdYA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.1
