cert-manager:
  enabled: true
  namespace: cert-manager
  fullnameOverride: cert-manager
  installCRDs: true
  webhook:
    fullnameOverride: cert-manager
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 200m
        memory: 256Mi

  cainjector:
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 200m
        memory: 256Mi

  controller:
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 200m
        memory: 256Mi

clusterIssuer:
  enabled: true
  ingressClass: traefik
  acme:
    email: dev@green-ecolution.de
    server: https://acme-v02.api.letsencrypt.org/directory
