namespace: cert-manager

cert-manager:
  enabled: true
  namespace: cert-manager
  fullnameOverride: cert-manager
  crds:
    enabled: true

clusterIssuer:
  enabled: true
  ingressClass: traefik
  acme:
    email: dev@green-ecolution.de
    server: https://acme-v02.api.letsencrypt.org/directory
