keycloak:
    auth:
        adminUser: ENC[AES256_GCM,data:hLBWB3g=,iv:bw9isQrDPE4X0zztTDGhisLaK5iV9eX2A7rkHMWimh8=,tag:l66DeiFzOKizo8tRChXeKw==,type:str]
        adminPassword: ENC[AES256_GCM,data:MqgEdL8V/vN4UlCz9zxLX+zPN4335B+F1V5mlkr3qPU=,iv:HBG8lvvqOKMOXvTLc4KgdWGtkM7vjE+o0PaDwV0mFsE=,tag:nIfwP9rkUEuV1MSr6rpr/w==,type:str]
    externalDatabase:
        user: ENC[AES256_GCM,data:xmTX9ZLBtLE=,iv:ld/Py4r8xN1TAoWROF1nxAgKoKuZiHysdmCXhvENQLE=,tag:NTL21VYqSjIsamKh+CgYDw==,type:str]
        password: ENC[AES256_GCM,data:lwerGXg6QxHOfFpb6xwaXOO7x5Yw0Oa8ZApSHih6+vI=,iv:4WUBo3wlG1+HsmKXPoKTwdW+f/xMaG85GtrfVxB2lJ4=,tag:d5sjK7tQzh+L5HuiPamk1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxL0tJdlcreW52UVBYR05N
            UWJWNnFrZGg3dEZrNzdjdGZld08wM0w0VFVZCmFOSDdoS3BmdlA5Uy9sYmttYmtT
            OFhTb3NocWs2cVd3RGxXNDNkbFozTXMKLS0tIGNPdjM4WjU1OU5PL2wxRUIzcEZH
            aGJncE14KzhSMUFEcXcvQ1h0cVhNZGsK+UmHK8gTPyobPXCmYzaLVXfkvvazG2AY
            oC4accava+vyVda/COc62a8wn4Rw6n37qV6ub7Zp8gcxHUs9sESKeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-21T10:13:18Z"
    mac: ENC[AES256_GCM,data:GTqbNVSzEydJnEwl9B/AGtKcuSSprl411+aqc28Xl9+X3TlVDOozN116AwUqlx+nDDVEgWIOgbe2Q/3SIlfAGtq6FaX/m8C5rPWtVYlWSA1Bf4r2ABIaWded0HEqRfy3eb+jN1iyG46t4Lw0XTeGPYCrAyAgD6Npb+/7bXrZYEc=,iv:DvRTAHPrKelFXqkRWWaXb+pCYNzlIXh7PLTk05TfWKs=,tag:BjxBSwvWU9ZJzS3mY3zoUA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
